function data_collection_csv_generation(N, R, O, A, ORD, AOD, ORR, AOR, half_sense, Op, Or, ad, alphaa, alphap, t)

dlmwrite(...
    'DirectionData.csv',...
    [...
    N,...
    R,...
    O,...
    A,...
    ORD,...
    AOD,...
    ORR,...
    AOR,...
    half_sense,...
    Op,...
    Or,...
    ad,...
    alphaa,...
    alphap,...
    t...
    ],...
    'delimiter',...
    ',',...
    '-append');

end


